### ISSUE TITLE
Manage /etc/rsyncd.conf

### ISSUE THREAD

**Issue by carlalexander** [debops/ansible-rsyslog#6]
Ran into this working with `debops.fail2ban`. By default, `rsyslogd` compresses messages which [messes with fail2ban](http://www.grosseosterhues.com/2011/02/securing-ssh-daemons-from-brute-force-attacks-in-ubuntu/). The solution is to change the `RepeatedMsgReduction` setting in `/etc/rsyncd.conf`.

`debops.rsyslog` doesn't manage this file at this time. Does it make sense to have it do it?

**Comment by drybjed** [comment]
I'm not sure what's the connection between `fail2ban`, `rsyslog` and `rsync`... I suppose that it's time to make a proper `rsyslog` role, with TLS and everything though. I'm working on `gitlab-runner` at the moment, after that I'll upgrade `rsyslog` role.

**Comment by carlalexander** [comment]
The rsyslog affects logs like `/var/log/auth.log` and compresses the log messages into this by default:
```console
Mar 10 18:59:08 test wordpress[32325]: (wordpress.example.org) Authentication failure for guest
Mar 10 18:59:59 test wordpress[32325]: message repeated 3 times: [ (wordpress.example.org) Authentication failure for guest ]
```
This affects anything using that log like the default ssh jail. It's also in the [community portal](http://www.fail2ban.org/wiki/index.php/Fail2ban:Community_Portal#Count_.22Last_message_repeated_N_times.22_correctly).

**Comment by carlalexander** [comment]
If you prefer to do it in `debops.fail2ban`, you could do something like this:
```yml
- name: Disable rsyslog message compression
  replace:
    dest: '/etc/rsyslog.conf'
    regexp: 'RepeatedMsgReduction on'
    replace: 'RepeatedMsgReduction off'
  notify: [ 'Restart fail2ban', 'Restart rsyslog' ]
```
You'd need an extra handler to restart rsyslog, but it gets the job done.
